version: '2.3'
services:
  notebook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: srcnn-pytorch
    shm_size: 32GB
    volumes:
      - ./:/workdir
      - ${DATASET_DIR}:/workdir/dataset
    working_dir: /workdir
    tty: true
    command: jupyter notebook --allow-root --ip 0.0.0.0 --port 8888
    runtime: nvidia
    env_file: .env
    environment:
      # workingdir に python の path を通すことで
      # プロジェクトルートに配置した自作のモジュールを import できるようにしている
      - PYTHONPATH=/workdir
      - TENSORBOARD_PORT=8000
    ports:
      # jupyter notebook
      - 8000:8888
      # tensorboard
      - 5001:8000
